#######################
# DyTox, for CIFAR100 #
#######################

# Model definition
model: ptvit
input_size: 224
dytox_pretrain: true
dytox: false

#batch_size: 64
#incremental_batch_size: 64

# Training setting
no_amp: false
eval_every: 250

# Base hyperparameter
epochs: 10
base_epochs: 10
lr: 0.0001
warmup_lr: 0.0001

weight_decay: 0.000001
batch_size: 128
incremental_batch_size: 128
incremental_lr: 0.0005
rehearsal: icarl_all

# Knowledge Distillation
auto_kd: true

# Finetuning
finetuning: balanced
finetuning_epochs: 20
ft_no_sampling: true

# Dytox model
freeze_task: [old_task_tokens, old_heads]
freeze_ft: [sab]

# Divergence head to get diversity
head_div: 0.1
head_div_mode: tr

# Independent Classifiers
ind_clf: 1-1
bce_loss: true


# Advanced Augmentations, here disabled

## Erasing
reprob: 0.0
remode: pixel
recount: 1
resplit: false

## MixUp & CutMix
mixup: 0.0
cutmix: 0.0
